### PR TITLE
Firebase from v3 to v4

### PR DESCRIPTION
**Pull request by Pitouli**
Firebase updated from v3.6.6 to v4.8.1: now include Firestore (Beta)

`this.$fireFS()` - return `window.firebase.firestore()`
`this.$fireFS('xxx')` - return `window.firebase.firestore().collection('xxx')`
`this.$fireFS('xxx/yyy')` (odd number of slashes) - return `window.firebase.firestore().doc('xxx/yyy')`
`this.$fireFS('xxx/yyy/zzz')` (even number of slashes) - return `window.firebase.firestore().doc('xxx/yyy').collection('zzz')`

In configuration:
"enableFirestore": true/false,
"enableFirestoreOffline": true/false,

### CODE REVIEW

**Comment by ileyd** [comment]
what's stopping this from being merged?

**Comment by josteph** [comment]
The author is still busy preparing for v2.0 release. This might be considered in v2.0 as well, thank you for contributing!

**Comment by scriptPilot** [comment]
@ileyd - Thank you for this pull request. I will test and merge it soon.

**Comment by ileyd** [comment]
@scriptPilot It's actually not my pull request :P

**Comment by livewithme** [comment]
how can i add toast plugin to this appframework , dashen?

**Comment by livewithme** [comment]
that's like this https://github.com/valnub/Toast-for-Framework7 ,my english is poor ,forgive me hah

**Comment by scriptPilot** [comment]
Firebase V5 will be used in App Framework V3

**Pull request closed without merging**
